<a href="https://colab.research.google.com/github/deepan98raj-dotcom/Assessment/blob/main/Logic_Gates_using_Perceptron_and_Neural_Network_(AND%2C_OR%2C_NOT%2C_XOR)_Assign_on_14_08_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install scikit-learn keras

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense

# load the Iris dataset
iris = load_iris()
X = iris.data
y = (iris.target == 0).astype(int)

In [ ]:

# Split the data into training and testing sets
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create a seqential model
model = Sequential()

# Add the input layer and the first hidden layer
model.add(Dense(units=6, activation='relu', input_dim=4))

# Add the second hidden layer
model.add(Dense(units=6, activation='relu'))

# Add the output layer
model.add(Dense(units=1, activation='sigmoid'))


In [ ]:
from keras.optimizers import Adam

# Compile the model
model.compile(optimizer =Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'] )

In [ ]:
# display the model summary
model.summary()


In [ ]:
# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=8, validation_split=0.2)

In [ ]:
ypred = model.predict(X_test)
ypred = (ypred > 0.5)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test loss:{loss:.4f}, Test Accuracy:{accuracy:.4f}')

In [ ]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

# --- Perceptron for Basic Logic Gates (AND, OR, NOT) ---

print("--- Perceptron for Basic Logic Gates ---")

def train_perceptron(X, y, gate_name):
    model = Perceptron(random_state=42, max_iter=1000, tol=1e-3)
    model.fit(X, y)
    y_pred = model.predict(X)
    accuracy = accuracy_score(y, y_pred)
    print(f"{gate_name} Gate Perceptron Accuracy: {accuracy:.2f}")
    print(f"{gate_name} Gate Predictions: {y_pred}\n")
    return model

# AND Gate
X_and = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])
print("AND Gate Inputs:\n", X_and)
print("AND Gate True Outputs:\n", y_and)
perceptron_and = train_perceptron(X_and, y_and, "AND")

# OR Gate
X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_or = np.array([0, 1, 1, 1])
print("OR Gate Inputs:\n", X_or)
print("OR Gate True Outputs:\n", y_or)
perceptron_or = train_perceptron(X_or, y_or, "OR")

# NOT Gate (requires single input, so reshape for perceptron)
X_not = np.array([[0], [1]])
y_not = np.array([1, 0])
print("NOT Gate Inputs:\n", X_not)
print("NOT Gate True Outputs:\n", y_not)
perceptron_not = train_perceptron(X_not, y_not, "NOT")


# --- Neural Network (MLPClassifier) for All Logic Gates (including XOR) ---

print("\n--- Neural Network (MLPClassifier) for All Logic Gates ---")

def train_mlp(X, y, gate_name):
    # For XOR, a single perceptron cannot solve it, so we need hidden layers.
    # For simple gates, a single layer might suffice, but we use a small hidden layer for consistency.
    model = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='lbfgs', max_iter=1000, random_state=42)
    model.fit(X, y)
    y_pred = model.predict(X)
    accuracy = accuracy_score(y, y_pred)
    print(f"{gate_name} Gate MLP Accuracy: {accuracy:.2f}")
    print(f"{gate_name} Gate Predictions: {y_pred}\n")
    return model

# AND Gate with MLP
print("AND Gate Inputs:\n", X_and)
print("AND Gate True Outputs:\n", y_and)
mlp_and = train_mlp(X_and, y_and, "AND")

# OR Gate with MLP
print("OR Gate Inputs:\n", X_or)
print("OR Gate True Outputs:\n", y_or)
mlp_or = train_mlp(X_or, y_or, "OR")

# NOT Gate with MLP
print("NOT Gate Inputs:\n", X_not)
print("NOT Gate True Outputs:\n", y_not)
mlp_not = train_mlp(X_not, y_not, "NOT")

# XOR Gate (classic example where a single perceptron fails)
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([0, 1, 1, 0])
print("XOR Gate Inputs:\n", X_xor)
print("XOR Gate True Outputs:\n", y_xor)
mlp_xor = train_mlp(X_xor, y_xor, "XOR")


--- Perceptron for Basic Logic Gates ---
AND Gate Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
AND Gate True Outputs:
 [0 0 0 1]
AND Gate Perceptron Accuracy: 1.00
AND Gate Predictions: [0 0 0 1]

OR Gate Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
OR Gate True Outputs:
 [0 1 1 1]
OR Gate Perceptron Accuracy: 1.00
OR Gate Predictions: [0 1 1 1]

NOT Gate Inputs:
 [[0]
 [1]]
NOT Gate True Outputs:
 [1 0]
NOT Gate Perceptron Accuracy: 1.00
NOT Gate Predictions: [1 0]


--- Neural Network (MLPClassifier) for All Logic Gates ---
AND Gate Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
AND Gate True Outputs:
 [0 0 0 1]
AND Gate MLP Accuracy: 1.00
AND Gate Predictions: [0 0 0 1]

OR Gate Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
OR Gate True Outputs:
 [0 1 1 1]
OR Gate MLP Accuracy: 1.00
OR Gate Predictions: [0 1 1 1]

NOT Gate Inputs:
 [[0]
 [1]]
NOT Gate True Outputs:
 [1 0]
NOT Gate MLP Accuracy: 1.00
NOT Gate Predictions: [1 0]

XOR Gate Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
XOR Gate True Outputs:
 [0 1 1 0]
XOR G