<a href="https://colab.research.google.com/github/deepan98raj-dotcom/Assessment/blob/main/Numpy%2C_Created_tuple%2Clist%2Cset_using_numpy%2COOPS_Concept%2C_File_Handling%2C_Exception_Handling_%26_Project_library_management_Assign_on_27_6_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The `def` keyword in Python is used to **define** a function.

# 1.**What is a function?**

A function is a block of organized, reusable code that is used to perform a single, related action. Functions provide better modularity for your application and a high degree of code reusing.

In [ ]:
def say_hello():
    print('hello')

say_hello()
say_hello()
say_hello()
say_hello()

hello
hello
hello
hello


# 2. Function Syntax

In [ ]:
def say_hello(name):
  print(f'Hello. Hi my dear Customer {name}. We have lovely. Choose your favorite.')

say_hello('deepan')

Hello. Hi my dear Customer deepan. We have lovely. Choose your favorite.


# 3. Calling a Function

Define a function does NOT execute it. we must call it using parenthesses ().


In [ ]:
def greet():
  print('Hello from greet function!')

greet()

Hello from greet function!


#4.Function with One Parameter

Parameters are inputs passed into a funtion. they allow the funtion to work with different values.

In [ ]:
def greet_user(name):
  print('Hello',name)

greet_user('Alice')
greet_user('Bob')
greet_user('Deepan')

Hello Alice
Hello Bob
Hello Deepan


# 5. Function with Multiple Parameters

A function can accept more than one input.


In [ ]:
def add_numbers(a,b):
   print(a+b)

add_numbers(10,20)
add_numbers(100,200)

30
300


# 6. Return Statement

```return``` sends data back to the place where the function was called. This allows further use of the result.

In [ ]:
def add(a,b):
  return a+b

result = add(10,20)
print(result)


30


# 7. print() vs return

### Coding Explanation

  * ```print()``` displays output on screen
  * ```return``` gives output back to the program

In [ ]:
def using_print():
  print(100)

def using_return():
  return 100

using_print()
value = using_print()
print(value)

using_return()
value = using_return()
print(value)

100
100
None
100


# 8. Default Parameters

Default values are used when no arguments is provided

In [ ]:
def country (name,country= 'india'):
  print(name,'is from',country)

country('deepan')
country('alex','USA')

deepan is from india
alex is from USA


# 9. Returning Multiple values

python allows returning multiple values using commas.

In [ ]:
def calculation (a,b):
    return a+b,a-b,a*b

s,d,m = calculation(10,5)
print(s,d,m)

15 5 50


# 10. Comman Beginner Mistakes

## Coding Explanation
    * forgetting parenthesses
    * wrong indentation
    * Expecting return when using print

# 11. Real - life Example

Coding Explantion

Funtion are used in billing systems,login systems,games, and AI models



In [ ]:
def calculate_bill(price,quantity):
  return price*quantity

total = calculate_bill(100,3)
print('Total bill:',total)

Total bill: 300


# Final Summary

## Coding Explanation
  
  * Functions make code reuable
  * Use ```def``` to defibe functions
  * Use parameters for input
  * Use ```return``` for output

Practice Tip : Write at least one function every day.

# Top 10 Python using for AI

Library -  part of coding used as per need
1. NumPy
2. Pandas
3. matplotlib
4. seaborn
5. scikit-learn
6. Tensorflow
7. keras
8. pytorch
9. open cv
10. XGBoost
11. Mlflow

# ways to import modules
  1. import module_name
  2. import module_name as alist
  3. from module_name import funtion
  4. from module_names import *
  

In [ ]:
import numpy as np

In [ ]:
from numpy import array

# 1. What is NumPy ?

NumPy is a Python library used to work with numbers very fast. It is mainly used when we have a lot of numerical data.

**Think of NumPy as :** A super-fast calculator for python.

# 2. Why Do we need NumPy ?

python lists are slow when data is very large.NumPy makes calculations faster and easier


In [ ]:
# Normal Python list

numbers = [10, 20, 30, 40]
print(numbers)

[10, 20, 30, 40]


In [ ]:
import numpy as np
# NumPy array

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


# 3. Creating Numpy Arrays

A NumPy array stores multiple numbers in one variable.


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


#4. Basic Math Operations

Numpy allows us to do math on all values at once.


In [ ]:
arr = np.array([10, 20, 30])
print(arr + 2)
print(arr - 2)
print(arr * 2)
print(arr / 2)

[12 22 32]
[ 8 18 28]
[20 40 60]
[ 5. 10. 15.]


# 5.indexing (Accessing Elements)

Index starts from 0. We can access values using position.

In [ ]:
arr = np.array([100, 200, 300])
print(arr[0])
print(arr[1])

100
200


# 6. Slicing (Getting part of Array)

slicing means taking a portition of the array


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


# 7. Shape and size

shape tells rows and columns. Size tells total number of elements.


In [ ]:
arr = np.array([[1,2,3,],[4,5,6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


# 8.Simple Statistics

NumPy can easily calculate sum, mean, and maximum value.



In [ ]:
marks = np.array([70, 80, 90, 60])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))



300
75.0
90


# 9. Real-life Example : Student Marks

We can analyze marks of many students easily using NumPy.


In [ ]:
marks = np.array([65,70,75,80,85])
print('Average:',np.mean(marks))

Average: 75.0


# 10. Comman Beginner Mistakes

  * Forgetting to import NumPy
  * Mixing list and array incorrectly


# Final Summary

  * Numpy is used for fast numerical operations
  * Arrays are faster than lists
  * Used in Data Science, ML, and AI

one-line numPY = fast math with Python




# 11. Creating Arrays

Different ways to create NumPy arrays.


In [ ]:
a = np.array([1,2,3,4,5])
b = np.zeros((4,2))
c = np.ones((4,4))
d = np.arange(0,10,2)
e = np.random.rand(3)
print(a, b, c, d, e, sep='\n')

[1 2 3 4 5]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.37207567 0.83415626 0.88974927]


# 12.Data Types(dtype)

Arrays store data specific data type

In [ ]:
arr = np.array([1,2,3], dtype = float)
print(arr.dtype)

float64


# 13. Shape , size , Dimensions

Understand array structure



In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(2, 3)
6
2


# 14. Reshaping

Change array shape without changing data.


In [ ]:
arr = np.arange(1,7)
print(arr)
print(arr.reshape(2,3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# 15. Indexing & Slicing

Access rows and columns easily.




In [ ]:
arr = np.array ([[10,20,30],[40,50,60]])
print(arr[0])
print(arr[:,1])

[10 20 30]
[20 50]


# 16. Boolean Indexing

Filter data using conditions

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[arr > 20])

[30 40 50]


# 17. Math Operations

Operations apply to all elememts.


In [ ]:
arr = np.array([1,2,3])
print(arr + 10)
print(arr * 3)
print(np.sqrt(arr))

[11 12 13]
[3 6 9]
[1.         1.41421356 1.73205081]


# 18. Statistical Operations

Built-in statistical functions.

In [ ]:
arr = np.array([10,20,30,40])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

100
25.0
40
10
11.180339887498949


# 19. Axis Concept

Axis controls row-wise or column-wise operations.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[5 7 9]
[ 6 15]


# 20. Broadcasting

Operations with different shapes.

In [ ]:
arr = np.array([1,2,3])
print(arr + 5)


[6 7 8]


# 21. Copy vs view

Memory behavior of arrays.


In [ ]:
Aa = np.array([1,2,3])
Bb = a.view()
Cc = a.copy()
Aa[0] = 100
print(Aa)
print(Aa,Bb,Cc)

[100   2   3]
[100   2   3] [1 2 3 4 5] [1 2 3 4 5]


# 13. Stack & split

Combine and divide arrays.



In [ ]:
a = np.array([1,2,10])
b = np.array([4,5,6])
print(np.concatenate((a,b)))
print(np.stack((a,b)))
print(np.hstack((a,b)))
print(np.vstack((a,b)))
print(np.dstack((a,b)))
print(np.array_split(a,3))

[ 1  2 10  4  5  6]
[[ 1  2 10]
 [ 4  5  6]]
[ 1  2 10  4  5  6]
[[ 1  2 10]
 [ 4  5  6]]
[[[ 1  4]
  [ 2  5]
  [10  6]]]
[array([1]), array([2]), array([10])]
